name: first_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.2
  connectivity_plus: ^6.0.3

  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.2.1
  go_router: ^14.2.0
  persistent_bottom_nav_bar_v2: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
